Cards:
  3 Main / Downtown:
    Starting Location: "Marine & Main"
    Stops:
      - Name: Marine Drive Station
        Colour: blue-large
      - Name: Marine & Main
        Colour: yellow
      - Name: 49th & Main
        Colour: yellow
      - Name: 41st & Main
        Colour: yellow
      - Name: 33rd & Main
        Colour: yellow
      - Name: King Edward & Main
        Colour: green
      - Name: 16th & Main
        Colour: green
      - Name: Broadway & Main
        Colour: green
      - Name: 2nd & Main
        Colour: green
      - Name: Main Street Station
        Colour: grey
      - Name: Hastings & Main
        Colour: grey
      - Name: Gastown
        Colour: grey
      - Name: Waterfront Station
        Colour: grey-large

  4 Powell / UBC:
    Starting Location: "Powell & Renfrew"
    Stops:
      - Name: Powell & Renfrew
        Colour: orange
      - Name: Powell & Nanaimo
        Colour: orange
      - Name: Powell & Commercial
        Colour: orange
      - Name: Powell & Clark
        Colour: orange
      - Name: Gastown
        Colour: grey
      - Name: Waterfront Station
        Colour: grey-large
      - Name: Vancouver City Centre Station
        Colour: grey-large
      - Name: Granville & Davie
        Colour: grey
      - Name: Granville Island
        Colour: red
      - Name: 4th & Arbutus
        Colour: red
      - Name: 4th & Macdonald
        Colour: white
      - Name: 4th & Alma
        Colour: white
      - Name: 4th & Blanca
        Colour: white
      - Name: UBC
        Colour: white-large

  7 Nanaimo Station / Dunbar:
    Starting Location: "Dunbar Loop"
    Stops:
      - Name: Nanaimo Station
        Colour: green
      - Name: Broadway & Nanaimo
        Colour: green
      - Name: 1st & Nanaimo
        Colour: orange
      - Name: Hastings & Nanaimo
        Colour: orange
      - Name: Powell & Nanaimo
        Colour: orange
      - Name: Powell & Commercial
        Colour: orange
      - Name: Powell & Clark
        Colour: orange
      - Name: Gastown
        Colour: grey
      - Name: Waterfront Station
        Colour: grey-large
      - Name: Vancouver City Centre Station
        Colour: grey-large
      - Name: Granville & Davie
        Colour: grey
      - Name: Granville Island
        Colour: red
      - Name: 4th & Arbutus
        Colour: red
      - Name: 4th & Macdonald
        Colour: white
      - Name: 4th & Alma
        Colour: white
      - Name: Broadway & Alma
        Colour: white
      - Name: 16th & Alma
        Colour: white
      - Name: King Edward & Dunbar
        Colour: white
      - Name: 33rd & Dunbar
        Colour: white
      - Name: Dunbar Loop
        Colour: white

  8 Fraser / Downtown:
    Starting Location: "Marine & Fraser"
    Stops:
      - Name: Marine & Fraser
        Colour: yellow
      - Name: 49th & Fraser
        Colour: yellow
      - Name: 41st & Fraser
        Colour: yellow
      - Name: 33rd & Fraser
        Colour: yellow
      - Name: King Edward & Fraser
        Colour: green
      - Name: Kingsway & Fraser
        Colour: green
      - Name: Broadway & Fraser
        Colour: green
      - Name: Broadway & Main
        Colour: green
      - Name: 2nd & Main
        Colour: green
      - Name: Main Street Station
        Colour: grey
      - Name: Hastings & Main
        Colour: grey
      - Name: Gastown
        Colour: grey
      - Name: Waterfront Station
        Colour: grey-large

  9 Boundary / UBC:
    Starting Location: "Boundary Loop"
    Stops:
      - Name: Boundary Loop
        Colour: purple
      - Name: Rupert Station
        Colour: purple
      - Name: Renfrew Station
        Colour: purple
      - Name: Broadway & Nanaimo
        Colour: green
      - Name: Commercial-Broadway Station
        Colour: green-large
      - Name: Broadway & Clark
        Colour: green
      - Name: Broadway & Fraser
        Colour: green
      - Name: Broadway & Main
        Colour: green
      - Name: Broadway-City Hall Station
        Colour: red-large
      - Name: Broadway & Oak
        Colour: red
      - Name: Broadway & Granville
        Colour: red
      - Name: Broadway & Arbutus
        Colour: red
      - Name: Broadway & Macdonald
        Colour: white
      - Name: Broadway & Alma
        Colour: white
      - Name: University Boulevard & Blanca
        Colour: white
      - Name: UBC
        Colour: white-large

  10 Granville / Downtown:
    Starting Location: "Marpole Loop"
    Stops:
      - Name: Marine Drive Station
        Colour: blue-large
      - Name: Marine & Oak
        Colour: blue
      - Name: Marpole Loop
        Colour: blue
      - Name: 49th & Granville
        Colour: blue
      - Name: 41st & Granville
        Colour: blue
      - Name: 33rd & Granville
        Colour: blue
      - Name: King Edward & Granville
        Colour: red
      - Name: 16th & Granville
        Colour: red
      - Name: Broadway & Granville
        Colour: red
      - Name: Granville Island
        Colour: red
      - Name: Granville & Davie
        Colour: grey
      - Name: Vancouver City Centre Station
        Colour: grey-large
      - Name: Waterfront Station
        Colour: grey-large

  14 Hastings / UBC:
    Starting Location: "Kootenay Loop"
    Stops:
      - Name: Kootenay Loop
        Colour: orange-large
      - Name: Hastings & Cassiar
        Colour: orange
      - Name: Hastings Park
        Colour: orange
      - Name: Hastings & Nanaimo
        Colour: orange
      - Name: Hastings & Commercial
        Colour: orange
      - Name: Hastings & Clark
        Colour: orange
      - Name: Hastings & Main
        Colour: grey
      - Name: Waterfront Station
        Colour: grey-large
      - Name: Vancouver City Centre Station
        Colour: grey-large
      - Name: Granville & Davie
        Colour: grey
      - Name: Granville Island
        Colour: red
      - Name: Broadway & Granville
        Colour: red
      - Name: Broadway & Arbutus
        Colour: red
      - Name: Broadway & Macdonald
        Colour: white
      - Name: Broadway & Alma
        Colour: white
      - Name: University Boulevard & Blanca
        Colour: white
      - Name: UBC
        Colour: white-large

  15/50 Waterfront Station / Olympic Village Station / Cambie:
    Starting Location: "Marine Drive Station"
    Stops:
      - Name: Waterfront Station
        Colour: grey-large
      - Name: Vancouver City Centre Station
        Colour: grey-large
      - Name: Granville & Davie
        Colour: grey
      - Name: Granville Island
        Colour: red
      - Name: False Creek
        Colour: red
      - Name: Olympic Village Station
        Colour: red
      - Name: Broadway-City Hall Station
        Colour: red-large
      - Name: 16th & Cambie
        Colour: red
      - Name: King Edward Station
        Colour: red
      - Name: Queen Elizabeth Park
        Colour: blue
      - Name: Oakridge/41st Station
        Colour: blue
      - Name: Langara/49th Station
        Colour: blue
      - Name: Marine Drive Station
        Colour: blue-large

  16 29th Avenue Station / Arbutus:
    Starting Location: "49th & West Boulevard"
    Stops:
      - Name: 29th Avenue Station
        Colour: purple
      - Name: 22nd & Renfrew
        Colour: purple
      - Name: Renfrew Station
        Colour: purple
      - Name: 1st & Renfrew
        Colour: orange
      - Name: Hastings Park
        Colour: orange
      - Name: Hastings & Nanaimo
        Colour: orange
      - Name: Hastings & Commercial
        Colour: orange
      - Name: Hastings & Clark
        Colour: orange
      - Name: Hastings & Main
        Colour: grey
      - Name: Waterfront Station
        Colour: grey-large
      - Name: Vancouver City Centre Station
        Colour: grey-large
      - Name: Granville & Davie
        Colour: grey
      - Name: Granville Island
        Colour: red
      - Name: Broadway & Granville
        Colour: red
      - Name: Broadway & Arbutus
        Colour: red
      - Name: 16th & Arbutus
        Colour: red
      - Name: King Edward & Arbutus
        Colour: red
      - Name: 33rd & Arbutus
        Colour: blue
      - Name: 41st & West Boulevard
        Colour: blue
      - Name: 49th & West Boulevard
        Colour: blue

  17 Oak / Downtown:
    Starting Location: "Marine & Oak"
    Stops:
      - Name: Marine Drive Station
        Colour: blue-large
      - Name: Marine & Oak
        Colour: blue
      - Name: 49th & Oak
        Colour: blue
      - Name: 41st & Oak
        Colour: blue
      - Name: 33rd & Oak
        Colour: blue
      - Name: King Edward & Oak
        Colour: red
      - Name: 16th & Oak
        Colour: red
      - Name: Broadway & Oak
        Colour: red
      - Name: Broadway-City Hall Station
        Colour: red-large
      - Name: Olympic Village Station
        Colour: red
      - Name: Yaletown-Roundhouse Station
        Colour: grey
      - Name: Vancouver City Centre Station
        Colour: grey-large
      - Name: Stadium-Chinatown Station
        Colour: grey
      - Name: Waterfront Station
        Colour: grey-large

  19 Metrotown Station / Stanley Park:
    Starting Location: "Metrotown Station"
    Stops:
      - Name: Metrotown Station
        Colour: purple-large
      - Name: Kingsway & Boundary
        Colour: purple
      - Name: Kingsway & 41st
        Colour: purple
      - Name: Kingsway & Slocan
        Colour: purple
      - Name: Kingsway & Nanaimo
        Colour: green
      - Name: Kingsway & Victoria
        Colour: green
      - Name: Kingsway & Knight
        Colour: green
      - Name: Kingsway & Fraser
        Colour: green
      - Name: Broadway & Main
        Colour: green
      - Name: 2nd & Main
        Colour: green
      - Name: Main Street Station
        Colour: grey
      - Name: Hastings & Main
        Colour: grey
      - Name: Waterfront Station
        Colour: grey-large
      - Name: Burrard Station
        Colour: grey
      - Name: Stanley Park
        Colour: grey

  20 Victoria / Downtown:
    Starting Location: "Marine & Victoria"
    Stops:
      - Name: Marine & Victoria
        Colour: yellow
      - Name: 49th & Victoria
        Colour: yellow
      - Name: 41st & Victoria
        Colour: yellow
      - Name: 33rd & Victoria
        Colour: yellow
      - Name: Kingsway & Victoria
        Colour: green
      - Name: 16th & Commercial
        Colour: green
      - Name: Commercial-Broadway Station
        Colour: green-large
      - Name: 1st & Commercial
        Colour: orange
      - Name: Hastings & Commercial
        Colour: orange
      - Name: Hastings & Clark
        Colour: orange
      - Name: Hastings & Main
        Colour: grey
      - Name: Waterfront Station
        Colour: grey-large
      - Name: Vancouver City Centre Station
        Colour: grey-large

  22 Knight / Macdonald:
    Starting Location: "Marine & Knight"
    Stops:
      - Name: Marine & Knight
        Colour: yellow
      - Name: 49th & Knight
        Colour: yellow
      - Name: 41st & Knight
        Colour: yellow
      - Name: 33rd & Knight
        Colour: yellow
      - Name: Kingsway & Knight
        Colour: green
      - Name: 16th & Knight
        Colour: green
      - Name: Broadway & Clark
        Colour: green
      - Name: VCC/Clark Station
        Colour: green
      - Name: 1st & Clark
        Colour: orange
      - Name: Main Street Station
        Colour: grey
      - Name: Hastings & Main
        Colour: grey
      - Name: Waterfront Station
        Colour: grey-large
      - Name: Burrard Station
        Colour: grey
      - Name: West End
        Colour: grey
      - Name: Vanier Park
        Colour: grey
      - Name: 4th & Macdonald
        Colour: white
      - Name: Broadway & Macdonald
        Colour: white
      - Name: 16th & Macdonald
        Colour: white
      - Name: King Edward & Mackenzie
        Colour: white
      - Name: 33rd & Mackenzie
        Colour: white
      - Name: 41st & Mackenzie
        Colour: white
      - Name: Dunbar Loop
        Colour: white

  25 Brentwood Station / UBC:
    Starting Location: "Brentwood Town Centre Station"
    Stops:
      - Name: Brentwood Town Centre Station
        Colour: purple-large
      - Name: 22nd & Boundary
        Colour: purple
      - Name: 22nd & Rupert
        Colour: purple
      - Name: 22nd & Renfrew
        Colour: purple
      - Name: Nanaimo Station
        Colour: green
      - Name: Kingsway & Nanaimo
        Colour: green
      - Name: Kingsway & Victoria
        Colour: green
      - Name: Kingsway & Knight
        Colour: green
      - Name: King Edward & Fraser
        Colour: green
      - Name: King Edward & Main
        Colour: green
      - Name: King Edward Station
        Colour: red
      - Name: King Edward & Oak
        Colour: red
      - Name: King Edward & Granville
        Colour: red
      - Name: King Edward & Arbutus
        Colour: red
      - Name: King Edward & Mackenzie
        Colour: white
      - Name: King Edward & Dunbar
        Colour: white
      - Name: 16th & Alma
        Colour: white
      - Name: 16th & Blanca
        Colour: white
      - Name: UBC
        Colour: white-large

  26-29 Kootenay Loop / Joyce Station / 29th Avenue Station / Elliott:
    Starting Location: "Marine & Elliott"
    Stops:
      - Name: Kootenay Loop
        Colour: orange-large
      - Name: 1st & Rupert
        Colour: orange
      - Name: 1st & Boundary
        Colour: orange
      - Name: Rupert Station
        Colour: purple
      - Name: Renfrew Station
        Colour: purple
      - Name: 22nd & Rupert
        Colour: purple
      - Name: 22nd & Boundary
        Colour: purple
      - Name: Joyce-Collingwood Station
        Colour: purple
      - Name: Kingsway & 41st
        Colour: purple
      - Name: Kingsway & Boundary
        Colour: purple
      - Name: 49th & Boundary
        Colour: purple
      - Name: 49th & Tyne
        Colour: purple
      - Name: 49th & Kerr
        Colour: purple
      - Name: 41st & Earles
        Colour: purple
      - Name: Kingsway & Slocan
        Colour: purple
      - Name: 29th Avenue Station
        Colour: purple
      - Name: 41st & Clarendon
        Colour: yellow
      - Name: 49th & Elliott
        Colour: yellow
      - Name: Marine & Elliott
        Colour: yellow

  33 29th Avenue Station / UBC:
    Starting Location: "29th Avenue Station"
    Stops:
      - Name: 29th Avenue Station
        Colour: purple
      - Name: Kingsway & Slocan
        Colour: purple
      - Name: 33rd & Victoria
        Colour: yellow
      - Name: 33rd & Knight
        Colour: yellow
      - Name: 33rd & Fraser
        Colour: yellow
      - Name: 33rd & Main
        Colour: yellow
      - Name: Queen Elizabeth Park
        Colour: blue
      - Name: King Edward Station
        Colour: red
      - Name: 16th & Cambie
        Colour: red
      - Name: 16th & Oak
        Colour: red
      - Name: 16th & Granville
        Colour: red
      - Name: 16th & Arbutus
        Colour: red
      - Name: 16th & Macdonald
        Colour: white
      - Name: 16th & Alma
        Colour: white
      - Name: 16th & Blanca
        Colour: white
      - Name: UBC
        Colour: white-large

  41 Joyce Station / UBC:
    Starting Location: "Joyce Station"
    Stops:
      - Name: Joyce Station
        Colour: purple
      - Name: Kingsway & 41st
        Colour: purple
      - Name: 41st & Earles
        Colour: purple
      - Name: 41st & Clarendon
        Colour: yellow
      - Name: 41st & Victoria
        Colour: yellow
      - Name: 41st & Knight
        Colour: yellow
      - Name: 41st & Fraser
        Colour: yellow
      - Name: 41st & Main
        Colour: yellow
      - Name: Oakridge/41st Station
        Colour: blue
      - Name: 41st & Oak
        Colour: blue
      - Name: 41st & Granville
        Colour: blue
      - Name: 41st & West Boulevard
        Colour: blue
      - Name: 41st & Mackenzie
        Colour: white
      - Name: Dunbar Loop
        Colour: white
      - Name: Southwest Marine Drive
        Colour: white
      - Name: UBC
        Colour: white-large

  44/84 Downtown / UBC / VCC-Clark Station:
    Starting Location: "UBC"
    Stops:
      - Name: Waterfront Station
        Colour: grey-large
      - Name: Burrard Station
        Colour: grey
      - Name: West End
        Colour: grey
      - Name: Vanier Park
        Colour: grey
      - Name: 4th & Macdonald
        Colour: white
      - Name: 4th & Alma
        Colour: white
      - Name: 4th & Blanca
        Colour: white
      - Name: UBC
        Colour: white-large
      - Name: 4th & Arbutus
        Colour: red
      - Name: Granville Island
        Colour: red
      - Name: False Creek
        Colour: red
      - Name: Olympic Village Station
        Colour: red
      - Name: 2nd & Main
        Colour: green
      - Name: Great Northern Way
        Colour: green
      - Name: VCC/Clark Station
        Colour: green

  49 Metrotown Station / UBC:
    Starting Location: "49th and Mackenzie"
    Stops:
      - Name: Metrotown Station
        Colour: purple-large
      - Name: 49th & Boundary
        Colour: purple
      - Name: 49th & Tyne
        Colour: purple
      - Name: 49th & Kerr
        Colour: purple
      - Name: 49th & Elliott
        Colour: yellow
      - Name: 49th & Victoria
        Colour: yellow
      - Name: 49th & Knight
        Colour: yellow
      - Name: 49th & Fraser
        Colour: yellow
      - Name: 49th & Main
        Colour: yellow
      - Name: Langara/49th Station
        Colour: blue
      - Name: 49th & Oak
        Colour: blue
      - Name: 49th & Granville
        Colour: blue
      - Name: 49th & West Boulevard
        Colour: blue
      - Name: 49th & Mackenzie
        Colour: white
      - Name: Dunbar Loop
        Colour: white
      - Name: Southwest Marine Drive
        Colour: white
      - Name: UBC
        Colour: white-large